language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
    - php: hhvm
    - php: hhvm-nightly

env:
  matrix:
    - LOWEST_DEPS=""
    - LOWEST_DEPS="--prefer-lowest"

services:
  - mysql

sudo: false

cache: vendor

before_script:
  - composer update --prefer-source $LOWEST_DEPS

script:
  - ./bin/atoum -c tests/.atoum.php -bf tests/.bootstrap.atoum.php

notifications:
  slack:
    rooms:
      secure: LVmBXAz0TKdB8dsB9Rt+M5+KnpStxEbOKuNVHN/lYOYmnB5CNogc/TDUKIFe5OUHAjGbn3xUy+tgBIME/RZLPAC6aAKpw0BPbGXYeagYlDBj9HUR9sUDrwV+l/75e4QWZPrUwS1dIa4ePirosIlYZwlwfGzEz8SgVY2x7BZFBEs=
