language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

script:
  - ./bin/atoum -c tests/.atoum.php -bf tests/.bootstrap.atoum.php
  - ./bin/phpcs  -p --standard=tests/phpcs/ruleset.xml lib/

before_script: composer install --dev
